#!/bin/sh

phenix.fmodel algorithm=direct scattering_table=it1992 \
     high_resolution=2.09  k_sol=0.443  b_sol=41.58  4phenix_3onk_noH.pdb

phenix.mtz.dump -f s -c 4phenix_3onk_noH.pdb.mtz | tr ',' '\t' > 4phenix_3onk_noH_ksol.443.fmodel.rdb

/bin/rm 4phenix_3onk_noH.pdb.mtz
