#!/bin/sh

export OMP_NUM_THREADS=8
export DO_PARALLEL=''

sander=/home/case/msander/bin/msander
if [ ! -z "$DO_PARALLEL" ]; then
   sander=$sander.MPI
fi

cat <<EOF > mdin
Test of MD with Xray restraints
 &cntrl
  imin=1, maxcyc=30,
  ntx = 1, irest = 0, ntpr = 2,  
  ntc = 2, ntf = 2, tol = 0.000001,
  cut = 10.0,
  nstlim = 5, dt = 0.001,
  ithermostat=1, therm_par=3., ig=827534,
  temp0 = 293.0, 
 /
 &ewald
  vdwmeth=0,
 /
 &xray
   spacegroup_name='P1',
   pdb_infile = '4phenix_3onk.pdb',
   reflection_infile = 'wbox-sf.dat',
   atom_selection_mask = '!(:Cl-,WAT)',
   xray_weight = 20000.0,
   fft_method = 0,
   target='ls', 
 /
 &debugf
  do_debugf=1, neglgdel=4, nranatm=0, atomn=1,5,6,7,
  chkvir=0, dumpfrc=0, rmsfrc=0, zerochg=0,
  zerovdw=0, do_dir=0, do_rec=0, do_adj=0, do_self=0,
  do_bond=0, do_angle=0, do_ephi=0, do_cap=0, doxconst=0,
  do_14=0, do_tgt=0, do_pbdir=0, do_pbnp=0, do_pbfd=0,
 /
EOF

$DO_PARALLEL $sander -O -i mdin -p 3onk.parm7 -c 4amber_3onk.rst7 \
    -o ls_debug.out \
    < /dev/null || { echo "  $0:  Program error"; exit 1; }

/bin/mv first.fmtz first_ml.fmtz

