#!/bin/sh

export OMP_NUM_THREADS=1
export DO_PARALLEL=''

sander=/home/case/msander/bin/msander
if [ ! -z "$DO_PARALLEL" ]; then
   sander=$sander.MPI
fi

cat <<EOF > mdin
Test of MD with Xray restraints
 &cntrl
  imin=0, maxcyc=1,
  ntx = 1, irest = 0, ntpr = 5,  
  ntc = 2, ntf = 2, tol = 0.000001,
  cut = 10.0,
  nstlim = 0, dt = 0.001,
  ithermostat=1, therm_par=3., ig=827534,
  temp0 = 293.0, 
 /
 &ewald
  vdwmeth=1,
 /
 &xray
   spacegroup_name='P1',
   pdb_infile = '4phenix_3onk.pdb'
   pdb_outfile = 'test.pdb',
   reflection_infile = 'wbox-sf.dat',
   atom_selection_mask = ':*',
   xray_weight = 1000.,
   fft_method = 0,
   target='ls', 
 /
EOF

$DO_PARALLEL $sander -O -i mdin -p 3onk.parm7 \
    -c 4amber_3onk.rst7  -o ls_test.o \
    < /dev/null || { echo "  $0:  Program error"; exit 1; }

/bin/mv first.fmtz first_ls.rdb

