#!/bin/bash
#######################################################################
#
#   slurm submission script for pmemd.cuda jobs
#
#   copy this script to your working directory, and make edits there
#
#######################################################################

JOB=krahn
output=krahn.o
STARTDIR=`pwd`

cat <<EOF2 > $JOB.pbs
#!/bin/bash -f
#SBATCH -N 1
#SBATCH -n 10
#SBATCH -t 100:00
#SBATCH -p main
#SBATCH --export=ALL
#SBATCH -o $JOB-%j.out
#SBATCH -e $JOB-%j.err


cd $STARTDIR

cat <<EOF > mdin
xray refinement of 4lzt
 &cntrl
  ntx=1, irest=0,
  cut=8.0,
  imin=0, maxcyc=1, ntpr=1,
  nstlim=50, dt=0.001,
  ithermostat=1,  therm_par=5.0, temp0 = 97.0, ig=-1,
  ntf=2, ntc=2, tol=0.000001, watnam='WAT ',
  ntr=0, restraint_wt=0.01, restraintmask=':1-274',
 /
 &xray
   spacegroup_name='P1',
   pdb_infile = 'w_4lzta.pdb',
   pdb_outfile = 'check.pdb',
   reflection_infile = '4lzt_phenix.fmtz',
   atom_selection_mask = ':1-274',
   xray_weight = 5000.
   fft_method = 0,
 /
EOF

mpirun -np 4 \
/home/case/msander/bin/msander.MPI  -O -i mdin -p 4lzta.parm7 \
      -c 4lzta.rst7 -o md1.o -r md1.x < /dev/null

/bin/rm mdin

EOF2

#sbatch $JOB.pbs
/bin/sh $JOB.pbs

