#!/bin/bash 

id=$1
resolution=$2

#--------------------------------------------------------------------------
#  1. Use metatwist to create a solvent density file from guv files:
#--------------------------------------------------------------------------

metatwist --dx $id.O.0.ccp4  --species O2-  --odx rho.O.0.ccp4  \
    --map rhoelreal --bulkdens 55.55 > metatwist.log
metatwist --dx $id.Na+.0.ccp4  --species Na+  --odx rho.Na+.0.ccp4  \
    --map rhoelreal --bulkdens 0.1 >> metatwist.log
metatwist --dx $id.Cl-.0.ccp4  --species Cl-  --odx rho.Cl-.0.ccp4  \
    --map rhoelreal --bulkdens 0.1 >> metatwist.log

metatwist --dx rho.O.0.ccp4 rho.Na+.0.ccp4 rho.Cl-.0.ccp4 \
     --odx solvent.ccp4 --species none >> metatwist.log

# mv rho.O.0.ccp4 solvent.ccp4   # replaces above if only water is present

# ================== convert to proper axis order for SFALL
mapmask mapin solvent.ccp4 mapout a.map <<EOF > metatwist.log
AXIS Z X Y
EOF

# =================== run SFALL
sfall mapin a.map hklout $id.mtz <<EOF >> metatwist.log
mode sfcalc mapin
RESO $resolution
EOF

# ==================== convert to rdb file to merge with an sf-dat file:
cat <<EOF > $id.fmtz
h	k	l	FC	PHIC
4N	4N	4N	10N	10N
EOF
phenix.mtz.dump -f s -c $id.mtz | tr ',' '\t' | awk 'NR>2' >> $id.fmtz

# /bin/rm -f $id.mtz a.map rho.*.ccp4  
